<?php
  include "header.php";
?>

<html>
    <head>
        <title>  Admin Page  </title>
    </head>
 				
<body style="background-color:white;">
<h1 style="color:navy; text-align: center;">Sales Associate Information</h1>

 <?php
  include "connection.php";
  //showing the inventory and everything in it

  $query = 'SELECT * FROM SalesAssociates';

  try{
        $statement = $pdo->prepare($query);
        $statement->execute();
        $rows = $statement->fetchAll(PDO::FETCH_ASSOC);
	$rowCount = $statement->rowCount();
  }catch(PDOException $e){

        die("<p>Query failed: {$e->getMessage()}</p>\n");
  }

  //table for inventory
  echo"<table border=1 style='margin-left: 200px; background-color; white; boarder-color: navy;'>";
  echo '<tr>';

 foreach (array_keys($rows[0]) as $heading) {
    echo "<td style='padding: 18px;'><strong>$heading<strong></td>";
  }
	echo "<td style='padding: 18px;'><strong>Action</strong></td>";
 	echo '</tr>';
 
  foreach($rows as $row){
      echo "<tr>";			
      foreach($row as $col){
	 echo "<td style='padding: 20px;'>$col</td>\n";
	} 
//adding buttons to tabel
echo "<td style='padding: 20px;'><button onclick='editRow(this)'>Edit</button><button onclick='confirmDelete(this)'>Delete</button></td>";
  echo "</tr>";
}

echo "</table>";

echo "<p> Total number of Employees: " . $rowCount . " </p>";

echo "<br/>";

echo "<button onclick='addAssociate()' style='font-size: 20px; color: navy;'>Add Associate</button>"; 

include "footer.php";

//button functionalities

echo "<script>
    function confirmDelete(button) {
        if (confirm('Are you sure you want to delete this employee?')) {
            var row = button.parentNode.parentNode;
	    row.parentNode.removeChild(row);
        }
     }
     function editRow(button) {
        var row = button.parentNode.parentNode;
        var cells = row.querySelectorAll('td');
        for (var i = 1; i < cells.length - 1; i++) { // Exclude action column
            var value = cells[i].innerText;
            cells[i].innerHTML = '<input type=\"text\" value=\"' + value + '\">';
        }
        var editButton = row.querySelector('button:nth-of-type(1)');
        editButton.innerHTML = 'Save';
        editButton.setAttribute('onclick', 'saveRow(this)');
     }
     function saveRow(button) {
        var row = button.parentNode.parentNode;
        var cells = row.querySelectorAll('td');
        var newData = [];
        var id = cells[0].innerHTML;
        for (var i = 1; i < cells.length - 1; i++) { 
            newData.push(cells[i].querySelector('input').value);
            cells[i].innerHTML = cells[i].querySelector('input').value;
        }
        var saveButton = row.querySelector('button:nth-of-type(1)');
        saveButton.innerHTML = 'Edit';
        saveButton.setAttribute('onclick', 'editRow(this)');
       fetch('./postSalesAssociate.php', {
          method: 'POST',
          headers: {'Content-Type': 'application/json'},
          body: JSON.stringify({
            SalesAssociateID: id,
            CommissionRate: newData[0],
            AssociateName: newData[1],
            AssociatePhone: newData[2],
            AssociateEmail: newData[3],
            AssociatePass: newData[4]
          })
        }).then(res => {
          res.text().then(data => {
            alert(data);
          })
        })
       }
function addAssociate() {
       var newRow = document.createElement('tr');
       newRow.innerHTML = '<td>(new)</td>' + // id is auto generated by the database
                           '<td><input type=\"text\"></td>' + 
                           '<td><input type=\"text\"></td>' + 
                           '<td><input type=\"text\"></td>' + 
                           '<td><input type=\"text\"></td>' + 
                           '<td><input type=\"password\"></td>' + 
                           '<td><button onclick=\"saveNewAssociate(this)\">Save</button></td>'; 
  document.querySelector('table tbody').appendChild(newRow);
}

function saveNewAssociate(button) {
        var row = button.parentNode.parentNode;
        var inputs = row.querySelectorAll('input[type=\"text\"], input[type=\"password\"]');
        var newRow = document.createElement('tr');
        var data = [];

       var idCell = document.createElement('td');
        newRow.appendChild(idCell);
        inputs.forEach(function(input) {
            var cell = document.createElement('td');
            cell.textContent = input.value;
            data.push(input.value);
            newRow.appendChild(cell);
        });

        fetch('./postSalesAssociate.php', {
          method: 'POST',
          headers: {'Content-Type': 'application/json'},
          body: JSON.stringify({
            SalesAssociateID: 'NEW',
            CommissionRate: data[0],
            AssociateName: data[1],
            AssociatePhone: data[2],
            AssociateEmail: data[3],
            AssociatePass: data[4]
          })
        }).then(res => {
          res.text().then(data => {
            alert(data);
          })
        })


        var actionCell = document.createElement('td');
        actionCell.innerHTML = '<button onclick=\"editRow(this)\"style=\'margin-left: 16px;\">Edit</button>' +
                               '<button onclick=\"confirmDelete(this)\">Delete</button>';
        newRow.appendChild(actionCell);
        document.querySelector('table tbody').appendChild(newRow);
        row.parentNode.removeChild(row);
    }


</script>";
?>

</body>
</html>



